(() => {
  "use strict";
  const renderer=window.CubeRenderer, key=renderer.key;
  const directions=[{x:1,y:0,z:0},{x:-1,y:0,z:0},{x:0,y:1,z:0},{x:0,y:-1,z:0},{x:0,y:0,z:1},{x:0,y:0,z:-1}];
  function normalize(cells) {
    const min={x:Math.min(...cells.map(c=>c.x)),y:Math.min(...cells.map(c=>c.y)),z:Math.min(...cells.map(c=>c.z))};
    return cells.map(c=>({x:c.x-min.x,y:c.y-min.y,z:c.z-min.z})).sort((a,b)=>a.x-b.x||a.y-b.y||a.z-b.z);
  }
  const signature=cells=>normalize(cells).map(key).join(";");
  function connected(cells) {
    if(!cells.length||new Set(cells.map(key)).size!==cells.length)return false;
    const all=new Set(cells.map(key)),seen=new Set([key(cells[0])]),queue=[cells[0]];
    for(let i=0;i<queue.length;i++)for(const d of directions){const c={x:queue[i].x+d.x,y:queue[i].y+d.y,z:queue[i].z+d.z},id=key(c);if(all.has(id)&&!seen.has(id)){seen.add(id);queue.push(c);}}
    return seen.size===cells.length;
  }
  const permutations=[[0,1,2],[0,2,1],[1,0,2],[1,2,0],[2,0,1],[2,1,0]];
  function orientations(cells) {
    const result=new Map();
    for(const permutation of permutations) {
      let inversions=0;for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)if(permutation[i]>permutation[j])inversions++;
      for(const sx of [-1,1])for(const sy of [-1,1])for(const sz of [-1,1]) {
        if(sx*sy*sz*(inversions%2?-1:1)!==1)continue; // only the 24 proper rotations
        const rotated=normalize(cells.map(c=>{const p=[c.x,c.y,c.z];return{x:sx*p[permutation[0]],y:sy*p[permutation[1]],z:sz*p[permutation[2]]};}));
        result.set(signature(rotated),rotated);
      }
    }
    return [...result.values()];
  }
  const rotationCache=new Map();
  function rotationSignature(cells) {
    const id=signature(cells);if(!rotationCache.has(id))rotationCache.set(id,orientations(cells).map(signature).sort()[0]);
    return rotationCache.get(id);
  }
  const fullCube=size=>Array.from({length:size**3},(_,i)=>({x:i%size,y:Math.floor(i/size)%size,z:Math.floor(i/(size*size))}));
  const coordinateValid=c=>c&&[c.x,c.y,c.z].every(Number.isInteger);
  function fits(puzzle,piece) {return Array.isArray(piece)&&piece.length===puzzle.missing.length&&signature(piece)===signature(puzzle.missing);}
  function visibleMissing(size,missing) {
    const removed=new Set(missing.map(key)),complete=fullCube(size);
    // Every removed cell has a visible exterior face, and nothing lies above
    // it. This keeps all information on-screen and allows insertion from above.
    if(!missing.every(c=>c.x===size-1||c.y===size-1||c.z===size-1))return false;
    for(const c of missing) for(const axis of ["x","y","z"]) for(let n=c[axis]+1;n<size;n++)if(!removed.has(key({...c,[axis]:n})))return false;
    const visible=new Set([...renderer.visibleTriangles(complete).values()].map(f=>key(f.cell)));
    return missing.every(c=>visible.has(key(c)))&&connected(complete.filter(c=>!removed.has(key(c))));
  }
  function validate(puzzle) {
    if(!puzzle||puzzle.size!==3||!['easy','hard'].includes(puzzle.difficulty)||!Array.isArray(puzzle.missing)||!Array.isArray(puzzle.remaining)||!Array.isArray(puzzle.options)||puzzle.options.length!==3)return false;
    const {size,missing,remaining,options}=puzzle,inside=c=>coordinateValid(c)&&[c.x,c.y,c.z].every(n=>n>=0&&n<size);
    if(!missing.every(inside)||!remaining.every(inside)||!connected(missing)||!connected(remaining))return false;
    const count=missing.length;if(puzzle.difficulty==='easy'?(count<2||count>3):(count<3||count>5))return false;
    if(puzzle.difficulty==='hard'&&['x','y','z'].filter(a=>new Set(missing.map(c=>c[a])).size>1).length<2)return false;
    const all=[...missing,...remaining];if(all.length!==size**3||new Set(all.map(key)).size!==size**3||!visibleMissing(size,missing))return false;
    if(!options.every(cells=>Array.isArray(cells)&&cells.length>=2&&cells.length<=5&&cells.every(inside)&&connected(cells)&&signature(cells)===cells.map(key).join(';')&&renderer.allVisible(cells)))return false;
    if(options.filter(piece=>fits(puzzle,piece)).length!==1)return false;
    const rotations=options.map(rotationSignature);if(new Set(rotations).size!==3)return false;
    const threshold=puzzle.difficulty==='easy'?.26:.14;
    for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)if(renderer.difference(options[i],options[j])<threshold)return false;
    return true;
  }
  // Small connected shape families, varied through proper rotations. They are
  // candidates only: holes are generated by growing a visible corner cut-out.
  const shapes=[
    [[0,0,0],[1,0,0]],
    [[0,0,0],[1,0,0],[2,0,0]],
    [[0,0,0],[1,0,0],[0,1,0]],
    [[0,0,0],[1,0,0],[0,1,0],[1,1,0]],
    [[0,0,0],[1,0,0],[2,0,0],[1,1,0]],
    [[0,0,0],[1,0,0],[1,1,0],[2,1,0]],
    [[0,0,0],[1,0,0],[2,0,0],[0,1,0]],
    [[0,0,0],[1,0,0],[0,1,0],[0,0,1]],
    [[0,0,0],[1,0,0],[2,0,0],[0,1,0],[0,0,1]],
    [[0,0,0],[1,0,0],[0,1,0],[1,1,0],[1,1,1]],
    [[0,0,0],[1,0,0],[2,0,0],[1,1,0],[1,0,1]],
    [[0,0,0],[1,0,0],[1,1,0],[2,1,0],[2,1,1]],
    [[0,0,0],[1,0,0],[2,0,0],[0,1,0],[0,2,0]]
  ].map(shape=>shape.map(([x,y,z])=>({x,y,z})));
  let pool;
  function candidates() {
    if(!pool){const unique=new Map();for(const shape of shapes)for(const piece of orientations(shape))if(renderer.allVisible(piece))unique.set(signature(piece),piece);pool=[...unique.values()];}
    return pool;
  }
  function randomIndex(length,random) {const value=Number(random());return Math.min(length-1,Math.max(0,Math.floor((Number.isFinite(value)?value:0)*length)));}
  function shuffled(array,random) {const result=[...array];for(let i=result.length-1;i>0;i--){const j=randomIndex(i+1,random);[result[i],result[j]]=[result[j],result[i]];}return result;}
  function makeMissing(difficulty,random) {
    const size=3,count=(difficulty==='hard'?3:2)+randomIndex(difficulty==='hard'?3:2,random);
    const missing=[{x:2,y:2,z:2}],removed=new Set(missing.map(key));
    const available=fullCube(size);
    while(missing.length<count) {
      const choices=available.filter(c=>!removed.has(key(c))&&(c.x===2||c.y===2||c.z===2)&&['x','y','z'].every(axis=>c[axis]===2||removed.has(key({...c,[axis]:c[axis]+1}))));
      if(!choices.length)return null;
      const chosen=choices[randomIndex(choices.length,random)];missing.push(chosen);removed.add(key(chosen));
    }
    if(difficulty==='hard'&&['x','y','z'].filter(axis=>new Set(missing.map(c=>c[axis])).size>1).length<2)return null;
    return missing;
  }
  function assemble(difficulty,missing,random) {
    const correct=normalize(missing),options=[correct],forms=new Set([rotationSignature(correct)]),threshold=difficulty==='easy'?.26:.14;
    let choices=shuffled(candidates().filter(p=>difficulty==='hard'?Math.abs(p.length-correct.length)<=1:p.length<=4),random);
    if(difficulty==='hard')choices.sort((a,b)=>Math.abs(a.length-correct.length)-Math.abs(b.length-correct.length));
    for(const candidate of choices) {
      const form=rotationSignature(candidate);
      if(forms.has(form)||options.some(p=>renderer.difference(p,candidate)<threshold))continue;
      options.push(candidate);forms.add(form);if(options.length===3)break;
    }
    if(options.length!==3)return null;
    const removed=new Set(missing.map(key));
    return {size:3,difficulty,missing,remaining:fullCube(3).filter(c=>!removed.has(key(c))),options:shuffled(options,random)};
  }
  function generate(difficulty='easy',random=Math.random) {
    difficulty=difficulty==='hard'?'hard':'easy';
    for(let attempt=0;attempt<24;attempt++) {
      const missing=makeMissing(difficulty,random);if(!missing)continue;
      const puzzle=assemble(difficulty,missing,random);if(puzzle&&validate(puzzle))return puzzle;
    }
    // A connected, open three-axis corner with a safe deterministic candidate set.
    const missing=difficulty==='hard'?[{x:2,y:2,z:2},{x:1,y:2,z:2},{x:2,y:1,z:2},{x:2,y:2,z:1}]:[{x:2,y:2,z:2},{x:1,y:2,z:2}];
    const puzzle=assemble(difficulty,missing,()=>.37);
    if(!validate(puzzle))throw new Error('Invalid cube fallback');
    return puzzle;
  }
  window.CubeGenerator=Object.freeze({normalize,signature,connected,rotationSignature,fullCube,fits,visibleMissing,validate,generate});
})();
